package avt;

import main.Canvas;

public final class T {
   public static String wedding;
   public static String pleaseWait;
   public static String menu;
   public static String close;
   public static String agree;
   public static String updateList;
   public static String update;
   public static String playNow;
   public static String strongest;
   public static String ready;
   public static String richest;
   public static String wearing;
   public static String cook;
   public static String start;
   public static String yes;
   public static String no;
   public static String viewMessage;
   public static String setMoney;
   public static String setNumPlayers;
   public static String setPass;
   public static String exitBoard;
   public static String kick;
   public static String continuee;
   public static String exit;
   public static String addFriend;
   public static String OK;
   public static String fire;
   public static String skip;
   public static String haBai;
   public static String xu;
   public static String gold;
   public static String noReady;
   public static String sapBaiXong;
   public static String numTienCuoc;
   public static String youAreKicked;
   public static String setPassed;
   public static String opponentQuit;
   public static String forceFinish;
   public static String sendMessage;
   public static String connecting;
   public static String logging;
   public static String selectt;
   public static String doYouWantExit2;
   public static String doYouWantSkip;
   public static String youMustFire3Bich;
   public static String notSameOrSmaller;
   public static String dola;
   public static String firstFire;
   public static String room;
   public static String goad;
   public static String ifPassword;
   public static String gameDraw;
   public static String buy;
   public static String friend;
   public static String option;
   public static String eat;
   public static String gett;
   public static String haPhom;
   public static String canYouOnceOnly;
   public static String yetSellectCard;
   public static String ifFireBreakPhom;
   public static String waitToCurrent;
   public static String notSamePhom;
   public static String youSelect;
   public static String notPhom;
   public static String viewMyInfo;
   public static String goToBoard;
   public static String moneyStr;
   public static String banChiCo;
   public static String aq = "vào";
   public static String ar = "/font.av";
   public static String as = "/bg.av";
   public static String at = "/home.av";
   public static String au = "/farm.av";
   public static String av = "/effect.av";
   public static String aw = "/main.av";
   public static String ax = "/dialLucky.av";
   public static String number;
   public static String priceStr;
   public static String nameStr;
   public static String pant;
   public static String setMaxMoney;
   public static String hair;
   public static String eye;
   public static String doYouWantBuy;
   public static String selectMoney;
   public static String aH = "http://";
   public static String aI = "@username";
   public static String youFirstFire;
   public static String inCome;
   public static String getFarmData;
   public static String enemyFirstFire;
   public static String storePro;
   public static String disConnect;
   public static String win;
   public static String lose;
   public static String draw;
   public static String give;
   public static String opponentAreNotReady;
   public static String exited;
   public static String complete;
   public static String areaIsFull;
   public static String area;
   public static String cardToMiss;
   public static String upTwoCard;
   public static String chat;
   public static String del;
   public static String beingOn;
   public static String watering;
   public static String land;
   public static String empty;
   public static String sell;
   public static String youWantBreakTree;
   public static String diarrhea;
   public static String flu;
   public static String hunger;
   public static String tire;
   public static String sixPointNoWin;
   public static String block2NoWin;
   public static String notOnFarm;
   public static String pw;
   public static String h;
   public static String seed;
   public static String item;
   public static String notOnFarmOther;
   public static String StoreSeed;
   public static String youAreBittenByDogByHound;
   public static String foodForEmpty;
   public static String moneySellPro;
   public static String mySeft;
   public static String next;
   public static String remem;
   public static String fogetPass;
   public static String nameAcc;
   public static String FAQs;
   public static String updateGame;
   public static String support;
   public static String delRMS;
   public static String alreadyDelRMS;
   public static String youUseNumRegGetpass;
   public static String removee;
   public static String connectFail;
   public static String cannotMove;
   public static String areYouAgreeRule;
   public static String chieuTuong;
   public static String pass;
   public static String cloth;
   public static String rememPass;
   public static String eventt;
   public static String giveGift;
   public static String hit;
   public static String kiss;
   public static String tkChinh;
   public static String tkFarm;
   public static String action;
   public static String feel;
   public static String exchange;
   public static String giveGiftFlower;
   public static String with;
   public static String refused;
   public static String index;
   public static String have;
   public static String loadMoney;
   public static String msgNew;
   public static String closeTab;
   public static String beginChat;
   public static String success;
   public static String createChar;
   public static String createCharFail;
   public static String cancel;
   public static String canHarvest;
   public static String container;
   public static String doYouWantDel;
   public static String trans;
   public static String doBen;
   public static String use;
   public static String sentMsg;
   public static String canNotSendMsg;
   public static String doYouWantExit;
   public static String viewInfo;
   public static String changePass;
   public static String finish;
   public static String toss;
   public static String bite;
   public static String miss;
   public static String numberFish;
   public static String achieve;
   public static String enterAgain;
   public static String giveGame;
   public static String sentToFriend;
   public static String phoneNumber;
   public static String youCanSelectFromMenu;
   public static String otherGame;
   public static String getData;
   public static String doYouWantExitIntoRegion;
   public static String day;
   public static String food;
   public static String dial;
   public static String doYouWantDial;
   public static String forever;
   public static String doYouWanBuyPrice;
   public static String sett;
   public static String homeRepait;
   public static String buyItem;
   public static String latGach;
   public static String sellItem;
   public static String noItem;
   public static String move;
   public static String rota;
   public static String doWantSellItem;
   public static String noPlaceItemHere;
   public static String haveItem;
   public static String setTuong;
   public static String noFriend;
   public static String goHome;
   public static String joinFrHome;
   public static String cho;
   public static String dunation;
   public static String inviteMyHouse;
   public static String won;
   public static String outHouse;
   public static String chay;
   public static String u;
   public static String denU;
   public static String youAreInvite;
   public static String doYouWant;
   public static String basket;
   public static String canNotConnect;
   public static String register;
   public static String uNeedExitGame;
   public static String Dial;
   public static String back;
   public static String youAreBittenByDog;
   public static String gift;
   public static String StoreEmtpy;
   public static String notTooGreedy;
   public static String usureStop;
   public static String milk;
   public static String cooking;
   public static String tkNew;
   public static String egg;
   public static String youWantBuyPro;
   public static String feedFor;
   public static String areYouUseNumReg;
   public static String disagree;
   public static String viewRule;
   public static String acc;
   public static String selectRegion;
   public static String privateMsg;
   public static String noQ;
   public static String doo;
   public static String detail;
   public static String face;
   public static String lvNotChange;
   public static String cap;
   public static String salonBeauty;
   public static String lvUse;
   public static String hasRob;
   public static String feeding;
   public static String info;
   public static String view;
   public static String doYouWantToTrade;
   public static String doYouWantUpgradeCoffer;
   public static String farmQuickCare;
   public static String farmCrop;
   public static String farmAnimal;
   public static String farmAutoCare;
   public static String farmKitchen;
   public static String farmWarehouse;
   public static String farmShop;
   public static String farmLobby;
   public static String farmSwitchAccount;
   public static String farmLogout;
   public static String farmComChao;
   public static String farmExit;
   public static String farmHarvest;
   public static String farmSowSeed;
   public static String farmTillSoil;
   public static String farmFertilize;
   public static String farmPestWeed;
   public static String farmWatering;
   public static String farmSellAnimal;
   public static String farmCollectProduce;
   public static String farmPumpTonic;
   public static String farmCureDisease;
   public static String datCuoc;
   public static String sendTo;
   public static String theft;
   public static String upgradeChest;
   public static String cityIsOffLine;
   public static String youAre;
   public static String doUWantCancel;
   public static String[] numPlayer;
   public static String[] constructing;
   public static String[] roomList;
   public static String[] roomName;
   public static String[] enterCard;
   public static String[] nameReg;
   public static String[] lister;
   public static String[] chatHeo;
   public static String[] enterPass;
   public static String[] emptyRoom;
   public static String[] gender;
   public static String[] login;
   public static String[] strName;
   public static String[] strTransMoney;
   public static String[] roomLevelText;
   public static String[] actionStr;
   public static String[] nameRegion;
   public static String[] selectLanguage;
   public static String[] enterPassReferral;
   public static String[] registerSuccess;
   public static String[] cannotRegister;
   private static String[] hd = new String[]{"/normal", "/medium", "/hd"};
   public static String[] cardTypeName;
   public static String[][] gettingPrice;
   public static String[][] sms;
   public static String[][] sendSmgFinish;
   public static String notEnough;
   public static String salePrice;
   public static String material;
   public static String done;
   public static String time;
   public static String QuickUpgrade;
   public static String harvest;
   public static String notSendSmg;
   public static String email;
   public static String utilities;
   public static String autoDialMenu;
   public static String utilChangeZone;
   public static String utilChangeMap;
   public static String utilAutoChat;
   public static String utilAutoKiss;
   public static String utilAutoKissAskOn;
   public static String utilAutoKissAskOff;
   public static String utilAutoKissNoFocus;
   public static String utilAutoHit;
   public static String utilAutoGift;
   public static String utilAutoTroll;
   public static String utilAutoClick;
   public static String utilStatus;
   public static String utilAutoTrollCode;
   public static String utilAutoTrollLimit;
   public static String utilAutoTrollIntervalMs;
   public static String utilAutoTrollSaveSuccess;
   public static String utilAutoGiftGiftId;
   public static String utilAutoGiftLimit;
   public static String utilAutoGiftLimitHint;
   public static String utilAutoGiftIntervalMs;
   public static String utilAutoGiftPayBy;
   public static String utilAutoGiftPayByHint;
   public static String utilAutoGiftSaveSuccess;
   public static String utilAutoClickKeyCode;
   public static String utilAutoClickStartKey;
   public static String utilAutoClickIntervalMs;
   public static String utilAutoClickSettingsNote;
   public static String utilAutoClickKeyList;
   public static String utilAutoClickSaveSuccess;
   public static String utilAutoClickNotifyToggle;
   public static String utilAutoClickEnabledNotice;
   public static String utilAutoClickDisabledNotice;
   public static String utilSpeed;
   public static String utilGameRoom;
   public static String utilVietnameseIME;
   public static String utilStateOn;
   public static String utilStateOff;
   public static String utilAutoClickStub;
   public static String utilGameRoomHint;
   public static String utilSpeedInputPrompt;
   public static String utilAutoChatBreak;
   public static String utilAutoChatContent;
   public static String utilAutoChatGuide;
   public static String utilAutoChatEnterContent;
   public static String utilAutoChatBack;
   public static String utilAutoChatSave;
   public static String utilAutoChatSaveSuccess;
   public static String utilAutoChatBreakPrompt;
   public static String utilAutoChatGuideBody;
   public static String utilMapSubSun;
   public static String utilMapSubGreenPark;
   public static String utilMapSubShop;
   public static String utilMapSubFun;
   public static String utilMapSubEco;
   public static String utilMapSubFarm;
   public static String utilStopAutoDial;
   public static String menuAuto;
   public static String menuAutoFishing;
   public static String menuAutoMining;
   public static String menuAutoFishingOn;
   public static String menuAutoFishingOff;
   public static String menuAutoFishingSettings;
   public static String loginPlayNew;
   public static String loginPlayContinue;
   public static String loginChangeAccount;
   public static String loginAddAccountShort;
   public static String loginSwitchAccountShort;
   public static String loginChangeLanguageMenu;
   public static String loginSwitchCharacter;
   public static String loginEmpty;
   public static String loginLoginBtn;
   public static String loginBack;
   public static String loginEdit;
   public static String loginDelete;
   public static String loginAdd;
   public static String loginEditAccount;
   public static String loginAddAccount;
   public static String loginPassword;
   public static String loginSave;
   public static String loginNoUsername;
   public static String loginNoPassword;
   public static String loginEmptyList;
   public static String loginNoAccountHint;
   public static String loginAddAccountSuccess;
   public static String loginDeleteAccountSuccess;
   public static String loginEmailOptional;
   public static String loginMobile;
   public static String loginOrEmail;
   public static String loginRegisterConfirm;
   public static String loginNewGameWarn;
   public static String loginEnterKey;
   public static String loginKeyRequired;
   public static String loginCheckingKey;
   public static String loginKeyConnectFail;
   public static String loginKeyInvalid;
   public static String loginKeyTooManyDevices;
   public static String loginKeyUsed;
   public static String loginKeyExpired;
   public static String loginKeyNotFound;
   public static String loginKeyManyDevicesClan;
   public static String loginNeedKeyBeforeLogin;
   public static String loginKeyExpiredKick;
   public static String loginKeyUsedOtherIp;
   public static String loginServerInfo;
   public static String langVi;
   public static String langId;
   public static String loginUsername;
   public static String utilAutoDialStopped;
   public static String eventNpcSettings;
   public static String eventGiftCounter;
   public static String eventGoFarm;
   public static String eventCheckin;
   public static String eventMenu;
   public static String mapAddNpc;
   public static String mapNpcList;
   public static String mapFishingSettings;
   public static String mapGive;
   public static String npcAutoPrefix;
   public static String npcAttackPrefix;
   public static String npcSearchSettings;
   public static String npcAttackSettings;
   public static String npcListEmpty;
   public static String npcDefaultName;
   public static String npcClearList;
   public static String npcNameKey;
   public static String npcNotPointed;
   public static String npcAlreadySaved;
   public static String npcSavedPrefix;
   public static String npcListCleared;
   public static String utilNpcKeyword;
   public static String utilCheckinContent;
   public static String utilZoneInterval;
   public static String utilScope;
   public static String utilScopeAllMaps;
   public static String utilScopeCurrentMap;
   public static String utilAttack;
   public static String utilAttackNone;
   public static String utilAttackType;
   public static String utilAttackContinuous;
   public static String utilAttackOnce;
   public static String utilAttackInterval;
   public static String utilAttackNote1;
   public static String utilAttackNote2;
   public static String utilSaveSettingsOk;
   public static String utilZoneIntervalInvalid;
   public static String utilAttackIntervalInvalid;
   public static String eventGiftCountPrefix;
   public static String eventResetCounter;
   public static String utilAutoStoneToggle;
   public static String utilAutoStoneSettings;
   public static String utilAutoStoneSellSettings;
   public static String utilAutoStoneSellForm;
   public static String utilAutoSell;
   public static String stonePebble;
   public static String stoneWhite;
   public static String stoneBlue;
   public static String stoneGreen;
   public static String stonePink;
   public static String stonePurple;
   public static String stoneGold;
   public static String stoneOrange;
   public static String stoneVoid;
   public static String utilAutoStoneSellSaved;
   public static String utilAutoStoneMineForm;
   public static String utilMineTime;
   public static String utilMineToggleKey;
   public static String utilMineOptions;
   public static String utilMineRecoverHealth;
   public static String utilMinePickaxeXuOpt;
   public static String utilMinePickaxeGoldOpt;
   public static String utilMineShovelXuOpt;
   public static String utilMineShovelGoldOpt;
   public static String utilMineLimitPickaxeXu;
   public static String utilMineLimitPickaxeGold;
   public static String utilMineLimitShovelXu;
   public static String utilMineLimitShovelGold;
   public static String utilUnlimited;
   public static String utilMiningPrefix;
   public static String utilMiningNone;
   public static String utilLimitPrefix;
   public static String utilPickaxePrefix;
   public static String utilPickaxeNone;
   public static String utilBoughtPrefix;
   public static String utilLimitSuffix;
   public static String utilNextBuyPrefix;
   public static String utilNextBuyNoSwitch;
   public static String utilNextBuyNone;
   public static String utilToolPickaxeXu;
   public static String utilToolPickaxeGold;
   public static String utilToolShovelXu;
   public static String utilToolShovelGold;
   public static String utilInvalidCode;
   public static String utilInvalidLimit;
   public static String utilInvalidInterval;
   public static String utilInvalidGift;
   public static String utilInvalidPayBy;
   public static String utilInvalidKeyCode;
   public static String utilInvalidStartKey;
   public static String utilInvalidMineTime;
   public static String utilInvalidToggleKey;
   public static String utilInvalidPickaxeXuLimit;
   public static String utilInvalidPickaxeGoldLimit;
   public static String utilInvalidShovelXuLimit;
   public static String utilInvalidShovelGoldLimit;
   public static String utilAutoStoneSaved;
   public static String fishResetCounter;
   public static String fishAutoLoginPrefix;
   public static String fishLoadingChest;
   public static String fishAutoLoginOn;
   public static String fishAutoLoginOff;
   public static String utilAttackYes;
   public static String npcFoundPrefix;
   public static String fishSettingsSaved;
   public static String fishCounterResetMsg;
   public static String utilSpeedResetMsg;
   public static String utilSpeedCurrentPrefix;
   public static String utilSpeedResetBtn;
   public static String fishAutoDropKcx;
   public static String fishKeepKcx;
   public static String fishSellList;
   public static String[] fishNames;
   public static String fishBuyTicket;
   public static String fishAutoBuyTicketOpt;
   public static String fishNoBuyTicket;
   public static String fishTicketType;
   public static String[] fishTicketTypes;
   public static String fishBuyRod;
   public static String fishAutoBuyRodOpt;
   public static String fishNoBuyRod;
   public static String fishRodType;
   public static String[] fishRodTypes;
   public static String fishAutoStoneGroup;
   public static String fishEnableAutoStone;
   public static String fishDisableAutoStone;
   public static String fishSellStoneGroup;
   public static String fishEnableSellStone;
   public static String fishDisableSellStone;
   public static String fishRedFieldToggle;
   public static String fishAutoBaitToggle;
   public static String fishAutoStoneToggle;
   public static String fishCaughtCountPrefix;
   public static String fishSoldCountPrefix;
   public static String utilSpeedInputRange;
   public static String npcListReadError;
   public static String npcIdInvalid;
   public static String utilChatSecondsRange;
   public static String fishDeveloping;
   public static String dialSpinningPrefix;
   public static String dialSpinningItem;
   public static String dialCountPrefix;
   public static String dialLimitPrefix;
   public static String dialDeleteJunk;
   public static String dialLimitField;
   public static String dialDelayField;
   public static String dialDelayNote;
   public static String dialInvalidValue;
   public static String dialLimitOff;
   public static String dialAutoLimitOff;
   public static String dialAutoLimitOnPrefix;
   public static String dialAutoLimitOnSuffix;
   public static String dialLimitReached;
   public static String dialForeverItemStop;
   public static String[] shopCategories;
   static String[][] textMiniMap;
   static String[][] textMapScr;
   static String[][] textMuaSam;
   static String[][] textToaThiChinh;
   static String[][] textFarmPath;
   static String[][] textFarm;
   static String[][] textShop;
   static String[][] textFish;
   static String[] textOut;

   public T() {
      applyLanguage(0);
   }

   public static void applyLanguage(int lang) {
      if (lang == 1) {
         TIndonesia.apply();
      } else {
         initVi();
      }
   }

   private static void initVi() {
      pleaseWait = "Xin chờ";
      menu = "Menu";
      close = "Đóng";
      agree = "Đồng ý";
      updateList = "Cập nhật";
      strongest = "Tìm bàn chơi";
      constructing = new String[]{"Tiến lên", "Phỏm", "Ba Lá", "Kim cương", "Bầu cua"};
      roomList = new String[]{"Kim cương", "Bầu cua", "Caro", "Cờ tướng", "Ongame"};
      String[] var10000 = new String[]{"Tiến lên", "Phỏm", "Caro", "Cờ tướng"};
      ready = "Sẵn sàng";
      richest = "Không s.sàng";
      start = "Bắt đầu";
      yes = "Có";
      no = "Không";
      viewMessage = "Tin nhắn";
      setMoney = "Đặt tiền cược";
      setNumPlayers = "Đặt số người";
      setPass = "Đặt mật khẩu";
      exitBoard = "Rời bàn";
      kick = "Đuổi";
      continuee = "Tiếp tục";
      exit = "Thoát";
      addFriend = "Kết bạn";
      OK = "OK";
      fire = "Đánh";
      skip = "Bỏ lượt";
      haBai = "Lật Bài";
      xu = "xu";
      gold = "lượng";
      noReady = "Lượng khóa";
      numPlayer = new String[]{"2 người", "3 người", "4 người"};
      sapBaiXong = "Sắp bài xong";
      numTienCuoc = "Số tiền cược";
      youAreKicked = "Bạn bị đuổi.";
      setPassed = "Đã đặt mật khẩu.";
      opponentQuit = "Đối thủ thoát. Bạn thắng";
      forceFinish = "Tới trắng";
      sendMessage = "Nhắn tin";
      connecting = "Đang kết nối";
      logging = "Đang đăng nhập";
      selectt = "Chọn";
      doYouWantExit2 = "Bạn có muốn thoát?";
      doYouWantSkip = "Bạn có chắc bỏ lượt?";
      youMustFire3Bich = "Bắt buộc đánh 3 bích trước.";
      notSameOrSmaller = "Không cùng loại hoặc nhỏ hơn bài đang trên bàn.";
      dola = "$";
      firstFire = " đi trước.";
      room = "Phòng ";
      goad = "Tới ";
      roomName = new String[]{"Cấp độ chính: ", "Cấp độ nông trại: ", "Cấp độ", "Cấp độ câu cá: "};
      ifPassword = "Password:";
      gameDraw = "Kết nối thất bại. Xin kiểm tra kết nối wifi/3g";
      buy = "Mua";
      friend = "Bạn bè";
      option = "Cài đặt";
      eat = "ăn";
      gett = "Nhận";
      haPhom = "Hạ Phỏm";
      canYouOnceOnly = "Bạn chỉ được đánh một lá.";
      yetSellectCard = "Bạn chưa chọn bài.";
      ifFireBreakPhom = "Nếu đánh lá này bạn sẽ phá phỏm";
      waitToCurrent = "Chờ đến lượt.";
      notSamePhom = "Không đúng phỏm.";
      youSelect = "Bạn chọn quá nhiều bài.";
      notPhom = "Không phải là phỏm.";
      viewMyInfo = "Xem thành tích";
      goToBoard = "Đến bàn số..";
      moneyStr = "Tiền: ";
      banChiCo = "Password:";
      aq = "vao";
      number = "Số lượng: ";
      priceStr = "Giá: ";
      nameStr = "Tên: ";
      pant = "Quần ";
      setMaxMoney = "áo ";
      hair = "Tóc ";
      eye = "Mắt ";
      doYouWantBuy = "Bạn có muốn mua không?";
      actionStr = new String[]{"Nhảy", "Nằm", "Ngồi bệt", "Quỳ"};
      selectMoney = "Bạn muốn mua bằng gì?";
      youFirstFire = "TK Chính";
      inCome = "Thu nhập: ";
      getFarmData = "Đang lấy dữ liệu nông trại...";
      enemyFirstFire = "Đang cập nhật dữ liệu..";
      storePro = "Kho hàng";
      roomLevelText = new String[]{"Phòng sơ cấp", "Phòng trung cấp", "Phòng cao thủ", "Phòng thi đấu"};
      disConnect = "Mất kết nối";
      win = "Thắng";
      lose = "Thua";
      draw = "Hòa";
      give = "Bỏ cuộc";
      opponentAreNotReady = "Đối thủ chưa sẵn sàng";
      exited = " đã thoát";
      sms = new String[][]{{"hiện", "ẩn", "Tên"}, {"hiện", "ẩn", "Chỉ đường"}, {"", "", "âm thanh"}, {"GPRS", "Wifi", "Kết nối"}, {"Tiếng việt", "Tiếng Anh", "Ngôn ngữ"}};
      complete = "Xong";
      areaIsFull = "Khu vực đã đầy.";
      area = "Khu vực ";
      cardToMiss = "Lá bài bạn đánh không có thực.";
      upTwoCard = "Năng ít nhất 2 lá để ăn.";
      chat = "Chat";
      del = "Xóa";
      nameRegion = new String[]{"Khu nhà ở", "Khu sinh thái", "Sân bay", "Khu giải trí", "Khu mua sắm", "Công viên", "Khu ngoại ô", "Nông trại"};
      beingOn = "Đang vào ";
      watering = "Tưới nước";
      land = "Làm đất";
      empty = "Đã hết ";
      sell = "Bán";
      youWantBreakTree = "Bạn muốn phá cây đang có?";
      diarrhea = "Bị tiêu chảy";
      flu = "Bị cúm";
      hunger = "Đói bụng";
      tire = "Mệt quá";
      sixPointNoWin = "Sữa";
      block2NoWin = "Trứng";
      notOnFarm = "Không vào được nông trại.";
      pw = "Bạn có muốn bán";
      h = " Giờ";
      seed = "Giống";
      item = "Vật Phẩm";
      notOnFarmOther = "Không thể vào.";
      StoreSeed = "Kho Giống";
      youAreBittenByDogByHound = "Bạn đã bị bắt.";
      foodForEmpty = "Hết thức ăn.";
      moneySellPro = "Tiền bán nông sản: ";
      mySeft = "Bản thân";
      next = "Tiếp";
      remem = "Nhớ";
      register = "Đăng ký";
      fogetPass = "Quên mật khẩu";
      nameAcc = "Tên tài khoản";
      FAQs = "Câu hỏi thường gặp";
      updateGame = "Cập nhật game";
      support = "Hỗ trợ";
      delRMS = "Xóa bộ nhớ tạm";
      alreadyDelRMS = "Đã";
      youUseNumRegGetpass = "Bạn phải dùng số điện thoại đăng ký tài khoản để lấy mật khẩu.";
      removee = "Bỏ";
      connectFail = "Không đồng ý";
      cannotMove = "Xem điều khoản";
      areYouAgreeRule = "Bạn phải chấp nhận điều khoản.";
      chieuTuong = "Tài khoản:";
      pass = "Mật khẩu";
      cloth = "Chọn T. Phố";
      rememPass = "Nhớ mật khẩu";
      eventt = "Sự kiện";
      giveGift = "Tặng quà";
      hit = "Đánh";
      kiss = "Hôn";
      tkChinh = "Xem thông tin";
      tkFarm = "Nhắn tin riêng";
      action = "Hành động";
      feel = "Cảm xúc";
      exchange = "Giao dịch";
      giveGiftFlower = " tặng hoa rơi cho ";
      with = " với ";
      refused = "Từ chối";
      sendSmgFinish = new String[][]{{"Số seri:", ""}, {"Mã số thẻ:", ""}};
      login = new String[]{"C.Độ: ", "T.Thiện", "G.Rối", "S.Điệu", "V.Vẻ", "S.Khỏe"};
      index = "Chỉ số";
      have = "Hiện có: ";
      strName = new String[]{"Nạp tiền", "Chuyển tiền", "Bản thân"};
      strTransMoney = new String[]{"TK chính sang nông trại", "TK nông trại sang chính"};
      loadMoney = "NẠP TIỀN";
      msgNew = "Tin đến";
      closeTab = "Đóng tab";
      beginChat = "Bắt đầu chat với ";
      success = "Xong";
      createChar = "Tạo nhân vật";
      gender = new String[]{"Nam", "Nữ"};
      createCharFail = "Tạo nhân vật không thành công.";
      cancel = "Hủy";
      canHarvest = "co the thu hoach";
      container = "Rương đồ";
      doYouWantDel = "Bỏ món đồ này ?";
      emptyRoom = new String[]{"Bỏ vào rương ?", "Sử dụng vật phẩm này ?", "Bỏ vào giỏ đồ ?", "Bỏ vào rương ?"};
      trans = "Di chuyển";
      doBen = "Độ bền: ";
      use = "Sử dụng";
      sentMsg = "Đã gửi tin nhắn.";
      canNotSendMsg = "Không thể gửi tin nhắn.";
      doYouWantExit = "Nếu thoát bạn sẽ bị xử thua. Bạn có muốn thoát?";
      lister = new String[]{"Nghe nhỏ", "Nghe vừa", "Nghe lớn"};
      cardTypeName = new String[]{"Cóc", "Sảnh", "Đôi", "Ba lá", "Ba đôi thông", "Bốn đôi thông", "Tứ quý"};
      chatHeo = new String[]{"Chặt heo đen", "Chặt heo đỏ", "Chặt đôi heo đen", "Chặt đôi heo đỏ", "Chặt đôi heo 1 đen 1 đỏ", "Chặt 3 đôi thông", "Chặt tứ quý", "Chặt 4 đôi thông"};
      viewInfo = "Thông tin";
      changePass = "Đổi mật khẩu";
      gettingPrice = new String[][]{{"Mật khẩu", "Cũ"}, {"Mật khẩu", "Mới"}, {"Nhập lại", "Mật khẩu"}};
      finish = "Xong";
      enterPass = new String[]{"Xin nhập mật khẩu hiện tại.", "Xin nhập mật khẩu mới.", "Xin nhập lại mật khẩu mới.", "Hai mật khẩu mới phải giống nhau.", "Mật khẩu mới phải khác mật khẩu cũ."};
      toss = "Quăng câu";
      bite = "Cắn câu";
      miss = "Trật rồi";
      numberFish = "Số cá câu được: ";
      achieve = "Thành tích";
      nameReg = new String[]{"Bạn chưa nhập tên", "Bạn chưa nhập mật khẩu", "Bạn chưa nhập lại mật khẩu.", "Hai mật khẩu không giống nhau."};
      enterAgain = "Nhập lại";
      var10000 = new String[]{"Hoa rơi", "Tim bay"};
      giveGame = "Tặng game cho..";
      sentToFriend = "Gui cho ban be";
      phoneNumber = "So dien thoai";
      youCanSelectFromMenu = "Ban co the chon so dien thoai tu Menu / Danh ba";
      otherGame = "Game khác";
      getData = "Bạn có muốn nâng cấp giỏ đồ không ?";
      doYouWantExitIntoRegion = "Bạn có muốn thoát game để vào mục này không?";
      enterCard = new String[]{"Bạn chưa nhập số seri.", "Bạn chưa nhập mã số thẻ."};
      day = "ngày";
      food = "Thức ăn";
      dial = "Quay số";
      doYouWantDial = "Ban có muốn quay số món đồ này không ?";
      forever = "Vĩnh viễn";
      doYouWanBuyPrice = "Bạn muốn mua vật phẩm này với giá";
      sett = "Đặt";
      homeRepait = "Chỉnh sửa nhà";
      buyItem = "Mua đồ";
      latGach = "lát gạch, sơn tường";
      sellItem = "Chuyển, bán đồ";
      noItem = "Không có vật phẩm ở đây";
      move = "Di chuyển";
      rota = "Xoay";
      doWantSellItem = "Bạn có muốn bán?";
      noPlaceItemHere = "Bạn không được đặt ở đây.";
      haveItem = "Đã có vật phẩm";
      setTuong = "Phải đặt sát tường.";
      noFriend = "Không có bạn trong khu này.";
      goHome = "Về nhà";
      joinFrHome = "Vào nhà bạn bè";
      cho = "cho";
      dunation = "tặng";
      inviteMyHouse = "Mời đến nhà";
      won = "Nâng cấp giỏ đồ";
      outHouse = "Bạn bị chủ nhà đuổi.";
      chay = "Cháy";
      u = "Ù";
      denU = "Đền ù";
      youAreInvite = "Bạn được mời về nhà bởi ";
      doYouWant = "Bạn có muốn không ?";
      basket = "Giỏ đồ";
      canNotConnect = "Không thể kết nối, xin kiểm tra lại GPRS/3G/Wifi.";
      uNeedExitGame = " Để chọn ngôn ngữ vui lòng khởi động lại game.";
      Dial = "Quay";
      selectLanguage = new String[]{"Tiến Lên", "Phỏm", "Kim Cương", "Bầu Cua", "Ba Lá", "Chuyển tiền"};
      back = "Quay về";
      wearing = "Đang mặc";
      youAreBittenByDog = "C.độ yêu cầu: ";
      gift = "Quà";
      StoreEmtpy = "Xin chào ";
      notTooGreedy = "Dừng";
      milk = "Bạn có muốn xem hướng dẫn chơi game không ?";
      usureStop = "Bạn có chắc muốn dừng hướng dẫn không?";
      cook = "Nấu ăn";
      cooking = "Đang nấu";
      doUWantCancel = "Bạn có muốn hủy món đang nấu không?";
      notEnough = "Không đủ ";
      salePrice = "Giá bán: ";
      material = "Nguyên liệu: ";
      done = "Hoàn thành";
      playNow = "Nấu ăn nhanh";
      time = "Thời gian: ";
      QuickUpgrade = "Nâng cấp nhanh";
      update = "Nâng cấp";
      harvest = "Thu hoạch";
      tkNew = "Tk game: ";
      wedding = "Quan hệ";
      egg = "Kho của bạn đã hết hạt giống, xin vào cửa hàng đễ mua.";
      youWantBuyPro = "Kho của bạn đã hết thuốc, xin vào cửa hàng đễ mua.";
      feedFor = "Bạn có muốn nâng cấp kho hàng không ?";
      areYouUseNumReg = "Không có vật nuôi nào bị bệnh";
      disagree = "ô này không có cây.";
      viewRule = "ô này không có cây.";
      acc = "Hãy chọn ô không có cây hoặc cây đã chết.";
      selectRegion = "Kho của bạn đã hết phân bón, xin vào cửa hàng đễ mua.";
      privateMsg = "Lông";
      noQ = "trom";
      doo = "Sản phẩm";
      detail = "Sản lượng";
      face = "Chăm sóc vật nuôi";
      lvNotChange = "Gieo hạt";
      cap = "Chăm sóc cây trồng";
      farmQuickCare = "Chăm sóc nhanh";
      farmCrop = "Cây trồng";
      farmAnimal = "Vật nuôi";
      farmAutoCare = "Chăm sóc tự động";
      farmKitchen = "Nhà bếp";
      farmWarehouse = "Kho hàng";
      farmShop = "Cửa hàng";
      farmLobby = "Sảnh nông trại";
      farmSwitchAccount = "Chuyển tài khoản";
      farmLogout = "Đăng xuất";
      farmComChao = "Cơm cháo";
      farmExit = "Thoát";
      farmHarvest = "Thu hoạch";
      farmSowSeed = "Gieo hạt";
      farmTillSoil = "Làm đất";
      farmFertilize = "Bón phân";
      farmPestWeed = "Diệt sâu cỏ";
      farmWatering = "Tưới nước";
      farmSellAnimal = "Bá vật nuôi";
      farmCollectProduce = "Thu nông phẩm";
      farmPumpTonic = "Bơm thuốc bổ";
      farmCureDisease = "Chữa bệnh";
      salonBeauty = "Trị bệnh";
      lvUse = "Kho của bạn đã hết thuốc tiêu chảy, xin vào cửa hàng đễ mua.";
      hasRob = "Kho của bạn đã hết thuốc cúm, xin vào cửa hàng đễ mua.";
      feeding = "Cho ăn";
      info = "Kho của bạn đã hết thức ăn, xin vào cửa hàng đễ mua.";
      view = "Thuốc bổ";
      doYouWantToTrade = "Kho của bạn đã hết thuốc bổ, xin vào cửa hàng đễ mua.";
      doYouWantUpgradeCoffer = "Bạn có muốn bất đầu lể cưới không ?";
      enterPassReferral = new String[]{"Lễ cưới của chú rể ", " và cô dâu ", " chính thức bắt đầu.  mời Cô Dâu và Chú rể cùng tiến về lễ đường."};
      registerSuccess = new String[]{"Hôm nay chúng ta có mặt tại đây để cùng chúc mừng cho đám cưới của chú rể ", "Vượt qua bao khó khăn thử thách bằng tình yêu vĩnh cửu, sau cùng cả hai đã đạt đến bến bờ hạnh phúc.", "Kể từ hôm nay, ta tuyên bố 2 bạn chính thức trở thành vợ chồng.", "Chú rể có thể hôn Cô Dâu."};
      datCuoc = "Đặt cược";
      sendTo = "Lịch sử";
      notSendSmg = "Bạn có muốn thoát không ?";
      theft = "Bạn có muốn thoát không (nếu có đặt cược bạn sẽ mất tiền cược) ?";
      upgradeChest = "Bản đặt cược";
      cannotRegister = new String[]{"Thấp", "Thường", "Cao"};
      cityIsOffLine = "Tỉ lệ";
      youAre = "Phong độ";
      email = "Sức khỏe";
      utilities = "Tiện ích";
      autoDialMenu = "Auto quay số";
      utilChangeZone = "Chuyển khu";
      utilChangeMap = "Chuyển map";
      utilAutoChat = "Auto chat";
      utilAutoKiss = "Auto kiss";
      utilAutoKissAskOn = "Để dùng Auto kiss, bạn cần chỉ vào người đó trước.?";
      utilAutoKissAskOff = "Tắt Auto kiss không?";
      utilAutoKissNoFocus = "Chưa chỉ vào người chơi. Hãy chọn người trên map rồi bật lại.";
      utilAutoHit = "Auto đánh";
      utilAutoGift = "Auto tặng quà";
      utilAutoTroll = "Auto troll";
      utilAutoClick = "Auto click";
      utilStatus = "Trạng thái";
      utilAutoTrollCode = "Mã";
      utilAutoTrollLimit = "Số lần(0 tức là không giới hạn)";
      utilAutoTrollIntervalMs = "Quãng nghỉ(ms)";
      utilAutoTrollSaveSuccess = "Đã lưu cài đặt auto troll.";
      utilAutoGiftGiftId = "ID quà tặng:";
      utilAutoGiftLimit = "Số lần(0 tức là không giới hạn)";
      utilAutoGiftLimitHint = "0: tắt giới hạn (lặp vô hạn)";
      utilAutoGiftIntervalMs = "Quãng nghỉ(mili giây):";
      utilAutoGiftPayBy = "Tặng bằng:";
      utilAutoGiftPayByHint = "1: xu 2: lượng";
      utilAutoGiftSaveSuccess = "Đã lưu cài đặt auto tặng quà.";
      utilAutoClickKeyCode = "Mã phím";
      utilAutoClickStartKey = "Phím khởi động";
      utilAutoClickIntervalMs = "Quãng nghỉ(ms)";
      utilAutoClickSettingsNote = "Bảng mã (nhập số vào Mã phím):";
      utilAutoClickKeyList = "Phím chọn giữa [OK]: -5\nPhím gọi: -10\nPhím chọn trái: -6\nPhím chọn phải: -7\nPhím chuyển lên: -1\nPhím chuyển xuống: -2\nPhím chuyển trái: -3\nPhím chuyển phải: -4\nPhím số 1: 49 | 2: 50 | 3: 51 | 4: 52 | 5: 53\nPhím số 6: 54 | 7: 55 | 8: 56 | 9: 57 | 0: 48\nPhím sao (*): 42 | Phím #: 35";
      utilAutoClickSaveSuccess = "Đã lưu cài đặt auto click.";
      utilAutoClickNotifyToggle = "Thông báo bật/tắt auto:";
      utilAutoClickEnabledNotice = "Đã bật auto click";
      utilAutoClickDisabledNotice = "Đã tắt auto click";
      utilSpeed = "Tốc độ";
      utilGameRoom = "Phòng game";
      utilVietnameseIME = "Gõ tiếng Việt";
      utilStateOn = "Bật";
      utilStateOff = "Tắt";
      utilAutoClickStub = "Auto click: chưa hỗ trợ trên máy này.";
      utilGameRoomHint = "Vào khu giải trí / NPC để mở phòng chơi.";
      utilSpeedInputPrompt = "Nhập tốc độ 1-100. Số càng nhỏ tốc độ càng nhanh.";
      utilAutoChatBreak = "Quãng nghỉ";
      utilAutoChatContent = "Cài đặt nội dung";
      utilAutoChatGuide = "Hướng dẫn sử dụng";
      utilAutoChatEnterContent = "Nhập nội dung";
      utilAutoChatBack = "Quay lại";
      utilAutoChatSave = "Lưu";
      utilAutoChatSaveSuccess = "Lưu nội dung chat thành công.";
      utilAutoChatBreakPrompt = "Nhập quãng nghỉ (giây) 1-120. Ví dụ 3 = mỗi 3 giây gửi một đoạn.";
      utilAutoChatGuideBody = "Tách nhiều câu bằng dấu /, game gửi luân phiên từng đoạn theo quãng nghỉ (giây), lặp vô hạn cho đến khi tắt. Ví dụ iuem/nvl gửi iu em, rồi vl, rồi lặp lại. Một đoạn không có / thì gửi lặp câu đó.";
      utilMapSubSun = "Khu mặt trời";
      utilMapSubGreenPark = "Công viên";
      utilMapSubShop = "Khu mua sắm";
      utilMapSubFun = "Khu giải trí";
      utilMapSubEco = "Khu sinh thái";
      utilMapSubFarm = "Sảnh nông trại";
      utilStopAutoDial = "Tắt auto quay số";
      menuAuto = "Menu Auto";
      menuAutoFishing = "Auto câu cá";
      menuAutoMining = "Auto đào đá";
      menuAutoFishingOn = "Bật auto";
      menuAutoFishingOff = "Tắt auto";
      menuAutoFishingSettings = "Cài đặt";
      loginPlayNew = "Chơi mới";
      loginPlayContinue = "Chơi tiếp";
      loginChangeAccount = "Đổi tài khoản";
      loginAddAccountShort = "Thêm TK";
      loginSwitchAccountShort = "Chuyển TK";
      loginChangeLanguageMenu = "Chuyển ngôn ngữ";
      loginSwitchCharacter = "Chuyển nhân vật";
      loginEmpty = "Trống";
      loginLoginBtn = "Đăng nhập";
      loginBack = "Quay lại";
      loginEdit = "Sửa";
      loginDelete = "Xóa";
      loginAdd = "Thêm";
      loginEditAccount = "Sửa tài khoản";
      loginAddAccount = "Thêm tài khoản";
      loginPassword = "Mật khẩu";
      loginSave = "Lưu";
      loginNoUsername = "Chưa nhập tài khoản.";
      loginNoPassword = "Chưa nhập mật khẩu.";
      loginEmptyList = "Danh sách trống.";
      loginNoAccountHint = "Chưa có tài khoản, hãy Thêm TK trước.";
      loginAddAccountSuccess = "Thêm tài khoản thành công";
      loginDeleteAccountSuccess = "Đã xóa tài khoản.";
      loginEmailOptional = "Tùy chọn";
      loginMobile = "Số di động";
      loginOrEmail = "hoặc email:";
      loginRegisterConfirm = "Bạn nên điền chính xác số di động hoặc email. Khi quên mật khẩu, bạn sẽ dùng nó để lấy lại. Bạn có chắc chắn đã điền số di động / email đúng chưa?";
      loginNewGameWarn = "Tài khoản của bạn chưa được đăng kí liên kết với một tài khoản Team. Bạn sẽ mất tài khoản đang chơi nếu tiếp tục. Bạn có muốn tiếp tục ?";
      loginEnterKey = "Nhập key";
      loginKeyRequired = "Vui lòng nhập key.";
      loginCheckingKey = "Đang kiểm tra key...";
      loginKeyConnectFail = "Không thể kết nối kiểm tra key.";
      loginKeyInvalid = "Key không hợp lệ hoặc đã hết hạn, vui lòng nhập lại.";
      loginKeyTooManyDevices = "Key của Bạn sử dụng quá nhiều máy!";
      loginKeyUsed = "Key đã được sử dụng.";
      loginKeyExpired = "Key đã hết hạn, vui lòng liên hệ Admin để tiếp tục sử dụng, Zalo: 0787054816";
      loginKeyNotFound = "Key không tồn tại";
      loginKeyManyDevicesClan = "Clan của Bạn sử dụng quá nhiều máy!";
      loginNeedKeyBeforeLogin = "Vui lòng nhập key trước khi đăng nhập.";
      loginKeyExpiredKick = "Key đã hết hạn, vui lòng nhập lại.";
      loginKeyUsedOtherIp = "Key đã được sử dụng ở IP khác.Nếu không phải bạn vui lòng liên hệ admin để được hỗ trợ";
      loginServerInfo = "Avatar 258 bản quyền thuộc Teamobi được phát triển và làm lại bởi Nguyễn Văn Bằng , Zalo : 0787054816";
      langVi = "Tiếng Việt";
      langId = "Bahasa Indonesia";
      loginUsername = "Username";
      utilAutoDialStopped = "Đã tắt auto quay số.";
      eventNpcSettings = "Cài đặt NPC";
      eventGiftCounter = "Bộ đếm quà";
      eventGoFarm = "Về nông trại";
      eventCheckin = "Báo danh sự kiện";
      eventMenu = "Menu event";
      mapAddNpc = "Thêm NPC";
      mapNpcList = "D.Sách Npc";
      mapFishingSettings = "Cài đặt câu cá";
      mapGive = "Tặng";
      npcAutoPrefix = "Auto NPC: ";
      npcAttackPrefix = "Tấn công: ";
      npcSearchSettings = "Cài đặt t.kiếm";
      npcAttackSettings = "Cài đặt t.công";
      npcListEmpty = "Danh sách NPC đang trống";
      npcDefaultName = "NPC";
      npcClearList = "Xoá d.sach npc";
      npcNameKey = "Tên NPC";
      npcNotPointed = "Chưa trỏ vào NPC";
      npcAlreadySaved = "NPC đã có trong bộ nhớ";
      npcSavedPrefix = "Đã lưu NPC: ";
      npcListCleared = "Đã xoá danh sách NPC";
      utilNpcKeyword = "Danh sách NPC (keyword)";
      utilCheckinContent = "Nội dung báo danh";
      utilZoneInterval = "Quãng nghỉ(ms) Chuyển khu";
      utilScope = "Phạm vi";
      utilScopeAllMaps = "Tất cả các map";
      utilScopeCurrentMap = "Chỉ map hiện tại";
      utilAttack = "Tấn công";
      utilAttackNone = "Không";
      utilAttackYes = "Có";
      utilAttackType = "Loại Tấn công";
      utilAttackContinuous = "Liên tục";
      utilAttackOnce = "Chỉ 1 lần";
      utilAttackInterval = "Quãng nghỉ(ms) Tấn công";
      utilAttackNote1 = "Lưu ý Auto Tấn công chỉ đi kèm";
      utilAttackNote2 = "khi NPC đó có trạng thái Tìm là";
      utilSaveSettingsOk = "Lưu cài đặt thành công";
      utilZoneIntervalInvalid = "Quãng nghỉ chuyển khu không hợp lệ";
      utilAttackIntervalInvalid = "Quãng nghỉ tấn công không hợp lệ";
      eventGiftCountPrefix = "Đã tặng (AutoGift): ";
      eventResetCounter = "Reset bộ đếm";
      utilAutoStoneToggle = "Bật/Tắt Auto: ";
      utilAutoStoneSettings = "Cài đặt auto";
      utilAutoStoneSellSettings = "Cài đặt auto bán đá";
      utilAutoStoneSellForm = "Cài đặt auto bán đá";
      utilAutoSell = "Tự bán";
      stonePebble = "Đá cuội";
      stoneWhite = "Đá trắng";
      stoneBlue = "Đá lam";
      stoneGreen = "Đá lục";
      stonePink = "Đá hồng";
      stonePurple = "Đá tím";
      stoneGold = "Đá vàng";
      stoneOrange = "Đá cam";
      stoneVoid = "Đá huyền không";
      utilAutoStoneSellSaved = "Đã lưu cài đặt auto bán đá";
      utilAutoStoneMineForm = "Cài đặt auto đào đá";
      utilMineTime = "Time đào (ms)";
      utilMineToggleKey = "Phím bật/tắt auto đào";
      utilMineOptions = "Tùy chọn";
      utilMineRecoverHealth = "Tự hồi phục sức khỏe";
      utilMinePickaxeXuOpt = "Auto cuốc thần kỳ xu";
      utilMinePickaxeGoldOpt = "Auto cuốc thần kỳ lượng";
      utilMineShovelXuOpt = "Auto cuốc thường xu";
      utilMineShovelGoldOpt = "Auto cuốc thường lượng";
      utilMineLimitPickaxeXu = "Giới hạn mua cuốc TK xu (0=ko giới hạn)";
      utilMineLimitPickaxeGold = "Giới hạn mua cuốc TK lượng (0=ko giới hạn)";
      utilMineLimitShovelXu = "Giới hạn mua cuốc thường xu (0=ko giới hạn)";
      utilMineLimitShovelGold = "Giới hạn mua cuốc thường lượng (0=ko giới hạn)";
      utilUnlimited = "Không giới hạn";
      utilMiningPrefix = "Đang đào: ";
      utilMiningNone = "Đang đào: Không có";
      utilLimitPrefix = "Giới hạn: ";
      utilPickaxePrefix = "Đang cuốc: ";
      utilPickaxeNone = "Đang cuốc: Không có (đã hết giới hạn)";
      utilBoughtPrefix = " | Đã mua: ";
      utilLimitSuffix = " | Giới hạn: ";
      utilNextBuyPrefix = "Đạt giới hạn sẽ mua: ";
      utilNextBuyNoSwitch = "Đạt giới hạn sẽ mua: (Không chuyển - Không giới hạn)";
      utilNextBuyNone = "Đạt giới hạn sẽ mua: Không có";
      utilToolPickaxeXu = "cuốc thần kỳ xu";
      utilToolPickaxeGold = "cuốc thần kỳ lượng";
      utilToolShovelXu = "cuốc thường xu";
      utilToolShovelGold = "cuốc thường lượng";
      utilInvalidCode = "Mã không hợp lệ";
      utilInvalidLimit = "Số lần không hợp lệ";
      utilInvalidInterval = "Quãng nghỉ không hợp lệ";
      utilInvalidGift = "Quà tặng không hợp lệ";
      utilInvalidPayBy = "Tặng bằng không hợp lệ";
      utilInvalidKeyCode = "Mã phím không hợp lệ";
      utilInvalidStartKey = "Phím khởi động không hợp lệ";
      utilInvalidMineTime = "Time đào không hợp lệ";
      utilInvalidToggleKey = "Phím bật/tắt không hợp lệ";
      utilInvalidPickaxeXuLimit = "Giới hạn cuốc TK xu không hợp lệ";
      utilInvalidPickaxeGoldLimit = "Giới hạn cuốc TK lượng không hợp lệ";
      utilInvalidShovelXuLimit = "Giới hạn cuốc thường xu không hợp lệ";
      utilInvalidShovelGoldLimit = "Giới hạn cuốc thường lượng không hợp lệ";
      utilAutoStoneSaved = "Đã lưu cài đặt Auto đào đá";
      fishResetCounter = "Reset bộ đếm";
      fishAutoLoginPrefix = "Auto login: ";
      fishLoadingChest = "Đang tải dữ liệu rương, hãy mở lại sau 1 giây.";
      fishAutoLoginOn = "Đã bật auto login";
      fishAutoLoginOff = "Đã tắt auto login";
      npcFoundPrefix = "Đã tìm thấy NPC: ";
      fishSettingsSaved = "Đã lưu cài đặt câu cá";
      fishCounterResetMsg = "Đã reset bộ đếm";
      utilSpeedResetMsg = "Đã reset tốc độ về 50";
      utilSpeedCurrentPrefix = "Tốc độ hiện tại: ";
      utilSpeedResetBtn = "Reset";
      fishAutoDropKcx = "Tự động bỏ KCX";
      fishKeepKcx = "Giữ KCX";
      fishSellList = "Danh sách cá cần bắn";
      fishNames = new String[]{"Cá chép vàng", "Cá rô", "Cá lồng tong", "Cá lóc", "Cá nóc", "Cua", "Cá mập", "Cá đuối", "Cá ngựa", "Cá chim"};
      fishBuyTicket = "Mua vé";
      fishAutoBuyTicketOpt = "Tự động mua vé";
      fishNoBuyTicket = "Không mua vé";
      fishTicketType = "Loại vé";
      fishTicketTypes = new String[]{"Vé câu cá rô ", "Vé câu cá lóc ", "Vé câu cá mập "};
      fishBuyRod = "Mua cần";
      fishAutoBuyRodOpt = "Tự động mua cần";
      fishNoBuyRod = "Không mua cần";
      fishRodType = "Loại cần";
      fishRodTypes = new String[]{"Cần câu tre", "Cần câu sắt", "Cần câu VIP"};
      fishAutoStoneGroup = "Auto đào đá";
      fishEnableAutoStone = "Bật auto đào đá";
      fishDisableAutoStone = "Không bật";
      fishSellStoneGroup = "Bán đá";
      fishEnableSellStone = "Có bán đá";
      fishDisableSellStone = "Không bán";
      fishRedFieldToggle = "Tự động bỏ KCX: ";
      fishAutoBaitToggle = "Auto mua mồi: ";
      fishAutoStoneToggle = "Auto đào đá: ";
      fishCaughtCountPrefix = "Số cá câu được: ";
      fishSoldCountPrefix = "Số cá đã bán: ";
      utilSpeedInputRange = "Nhập số 1-100";
      npcListReadError = "Không đọc được danh sách NPC.";
      npcIdInvalid = "ID NPC không hợp lệ";
      utilChatSecondsRange = "Nhập số giây 1-120";
      fishDeveloping = "Đang phát triển";
      dialSpinningPrefix = "Đang quay: ";
      dialSpinningItem = "Item";
      dialCountPrefix = "Số lần quay: ";
      dialLimitPrefix = "Giới hạn: ";
      dialDeleteJunk = "Xóa đồ rác";
      dialLimitField = "Số lần(0 tức là không giới hạn)";
      dialDelayField = "Quãng nghỉ(ms) - Quay số";
      dialDelayNote = "Lưu ý: Nếu cho phép bạn hãy chỉnh Quãng nghỉ thấp hơn để quay nhanh hơn.";
      dialInvalidValue = "Giá trị không hợp lệ!";
      dialLimitOff = "Đóng";
      dialAutoLimitOff = "Auto Quay Số - Giới hạn: Đóng.";
      dialAutoLimitOnPrefix = "Auto Quay Số giới hạn: ";
      dialAutoLimitOnSuffix = " lần.";
      dialLimitReached = "Đã đến giới hạn quay!";
      dialForeverItemStop = "Đã ra item vĩnh viễn, dừng Auto Quay Số.";
      shopCategories = new String[]{"Áo", "Quần", "Trang sức", "Nón", "Cầm tay", "Khác"};
      sms[4][0] = "Tiếng việt";
      sms[4][1] = "Bahasa Indonesia";
      textMiniMap = new String[][]{{"Chào mừng bạn đến với Avatar - Thành phố Tu", "Chúng ta sẽ dạo một vòng qua thành phố này nhé!", "Thành phố có rất nhiều khu, chúng ta sẽ đến từng khu để tìm hiểu", "Khu Giải Trí là nơi nào nhiệt nhất thành phố. Mời bạn chọn vào nào!"}, {"Nông Trại là nơi trồng trọt và chăn nuôi, bạn có thể tăng thêm thu nhập", "Bạn hãy chọn vào mục Nông Trại nào"}, {"Tiếp theo là khu Mua Sắm, nơi mà bạn có thể lựa chọn cho mình những bộ trang phục đẹp mắt.", "Chọn vào tham quan khu Mua Sắm ngay bạn nhé!"}, {"Tiếp theo là khu Sinh Thái, nơi mà bạn có thể thư giãn với việc câu cá", "Mời bạn chọn vào Khu Sinh Thái"}, {"Khu vực Công Viên là nơi bạn có thể gặp gỡ và trò chuyện với bạn bè", "Bạn có thể vào thử Công Viên. Sau khi dạo một vòng hãy đến Trạm Xe Buýt để trở lại nơi này nhé!"}, {"Thành phố diệu kỳ còn rất nhiều khu khác để bạn khám phá. Hãy ghé qua khu sân bay thường xuyên để cập nhật các địa điểm mới", "Giờ bạn có thể vào nông trại, vào hội cờ, đi mua sắm,đi câu cá, hoặc làm bất kỳ điều gì bạn thích. Cám ơn bạn đã xem hướng dẫn!"}};
      textMapScr = new String[][]{{"Chào mừng bạn đến khu giải trí.", "Nơi đây gồm hội quán cờ, Tòa thị chính, Trường đua pet sôi động và các gian hàng quay số may mắn cùng với đấu giá ngược."}, {"Đây là tòa thị chính, nơi bạn có thể nhận những nhiệm vụ trong game và xin gia nhập vào các hội nhóm.", "Hãy di chuyển nhân vật đến tham quan tòa thị chính đi nào!"}, {"Đây là trường đua thú sôi động. Bạn có thể vào xem những trận đua thú vô cùng hấp dẫn.", "Hãy tham quan trường đua trước khi chúng ta di chuyển sang khu vực khác nhé!"}};
      textMuaSam = new String[][]{{"Chào mừng bạn đến khu mua sắm, tại đây bạn có thể thỏa thích lựa chọn cho mình những bộ thời trang đẹp mắt và cá tính.", "Đầu tiên mời bạn vào Shop tham quan. Hãy di chuyển nhân vật đến shop nào."}, {"Đây là nhà bán thú nuôi, nơi bạn có thể lựa chọn cho mình những chú pet thật xinh xắn.", "Hãy vào xem một chút nhé!"}, {"Bạn có thể vào thay đổi kiểu tóc và mắt của mình tại Thẩm Mỹ Viện.", "Hãy vào tham quan thử nhé!"}};
      textToaThiChinh = new String[][]{{"Hãy gặp thị trưởng để nhận nhiệm vụ và gặp NPC Hội Nhóm để xin gia nhập vào các hội nhóm."}};
      textFarmPath = new String[][]{{"Khu vực nông trại có 4 nơi bạn có thể vào: Cửa hàng, ATM, Nông trại của mình, và Nông trại của bạn bè.", "Cửa hàng là nơi bạn mua hạt giống, vật nuôi và các vật phẩm khác", "Tại sao bạn lại không thử mua một ít hạt giống nhỉ?"}, {"Hiện tại trong người của bạn có sẵn vài hạt giống. Nhưng bạn vẫn có thể mua thêm hạt giống khác nếu thích.", "Hãy chọn mua thử nào!"}, {"Hãy chọn số lượng muốn mua", "Sau khi mua xong, bạn hãy chọn Đóng để rời khỏi cửa hàng"}, {"Chúng ta đã có một số hạt giống rồi!", "Hãy bước vào khu vực nông trại của bạn để bắt đầu gieo hạt!"}};
      textFarm = new String[][]{{"Đây là nông trại của bạn", "Chúng ta sẽ bắt đầu trải nghiệm làm một người nông dân chăm chỉ nhé!", "Bạn có thấy những ô đất không?", "Đây là khu vực bạn có thể trồng cây.", "Bắt đầu thôi nào! Bạn hãy di chuyển đến đó và chọn một ô đất", "Hãy chọn mục Làm Đất để xới đất nào!"}, {"Chúc mừng! Bạn đã hoàn thành xong việc làm đất", "Tiếp theo bạn hãy chọn hạt giống."}, {"Bạn đã gieo hạt. Trên mỗi ô đất có hiển thị thời gian bạn có thể thu hoạch được", "Bạn hãy thường xuyên vào tưới nước, bón phân cho cây cho đến khi thu hoạch nhé!"}, {"Đây là khu chăn nuôi gia súc.", "Bạn cần mua gia súc ngoài cửa hàng và thả nó vào đây", "hãy chăm sóc nó, cho ăn và tiêm thuốc bổ đều đặn, đến khi lớn bạn có thể thu hoạch sữa và trứng"}, {"Đây là nhà bếp, nơi bạn có thể nấu những món ăn từ nông sản bạn thu hoạch được."}, {"Đây là cây khế, cây khế sẽ cho thu hoạch trong thời gian nhất định.", "Hãy nâng cấp cây khế lên càng cao, sản lượng thu hoạch sẽ càng nhiều bạn nhé!"}, {"Bạn có thể nuôi cá trong ao này bằng cách mua cá từ cửa hàng bên ngoài", "Sau khi thu hoạch cây, vật nuôi, bạn sẽ có một khoản tiền nhỏ trong tài khoản nông trại", "Bạn có thể ra ATM để chuyển sang tài khoản chính để có thể dùng nhé!"}};
      textShop = new String[][]{{"Chào mừng bạn đến với cửa hàng quần áo.", "Hãy bước đến gặp người bán hàng để thử quần áo, bạn nhớ chú ý giá cả nhé!"}, {"Sử dụng các mũi tên để chọn các bộ quần áo khác nhau", "Nếu bạn có đủ tiền, hãy chọn mua một bộ quần áo mới"}};
      textFish = new String[][]{{"Chào mừng bạn đến với khu câu cá.", "Có 3 khu câu cá khác nhau, với 3 cấp độ khác nhau"}, {"Khu câu cá rô dành cho người mới tập câu"}, {"Khu câu cá lóc dành cho các bạn đã biết câu"}, {"Khu câu cá mập dành cho các bạn đã là cao thủ câu cá"}, {"Để có thể câu cá bạn phải mua cần câu, mồi câu, vé câu"}, {"Để có thể mua bạn có thể chat chữ cauca cửa hàng sẽ tự động hiện lên"}, {"Hoặc chat chữ banca nếu bạn muốn bán cá"}, {"Giờ chúng ta sẽ rời nơi này. Bạn có thể đến đây bất cứ khi nào bạn muốn!"}};
      textOut = new String[]{"Bạn có thể ra khỏi nơi này bằng cách đi đến nơi mũi tên chỉ"};
   }

   public static String getPath() {
      return hd[Canvas.stypeInt];
   }

   public static String[][] getTextMiniMap() {
      return textMiniMap;
   }

   public static String[][] getTextMapScr() {
      return textMapScr;
   }

   public static String[][] getTextMuaSam() {
      return textMuaSam;
   }

   public static String[][] getTextToaThiChinh() {
      return textToaThiChinh;
   }

   public static String[][] getTextFarmPath() {
      return textFarmPath;
   }

   public static String[][] getTextFarm() {
      return textFarm;
   }

   public static String[][] getTextShop() {
      return textShop;
   }

   public static String[][] getTextFish() {
      return textFish;
   }

   public static String[] getTextOut() {
      return textOut;
   }

   public static String getMoney() {
      return MapScr.isNewVersion ? "xeng" : xu;
   }

   public static String getMoneyH() {
      return MapScr.isNewVersion ? "xèng" : xu;
   }
}
